name: Run Scraper Daily

on:
  workflow_dispatch:  # मैन्युअल रन के लिए
  schedule:
    - cron: '10 11 * * 1-5'  # सोमवार से शुक्रवार रोज़ शाम 5 बजे IST (11:30 AM UTC)

jobs:
  run_scraper:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.13'

      - name: Show Python Version
        run: python --version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper with secret
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: python main.py
